=== GrottoCenter/UIS_Cave_symbols/additional_text.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Tobias Dahinden (Institute of Cartography) -->
<!--DTD generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<!ELEMENT li (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT croatian (p | ul)+>
<!ELEMENT dutch (p | ul)+>
<!ELEMENT english (p | ul)+>
<!ELEMENT french (p | ul)+>
<!ELEMENT german (p | ul)+>
<!ELEMENT italian (p | ul)+>
<!ELEMENT portuguese (p | ul)+>
<!ELEMENT romanian (p | ul)+>
<!ELEMENT slovene (p | ul)+>
<!ELEMENT turkish (p | ul)+>
<!ELEMENT text (croatian, dutch, english, french, german, italian, portuguese, romanian, slovene, turkish)>
<!ATTLIST text
	id ID #REQUIRED
>
<!ELEMENT texts (text+)>
<!ATTLIST texts
	xmlns:xsi CDATA #REQUIRED
	xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!ELEMENT ul (li+)>

=== GrottoCenter/UIS_Cave_symbols/additional_text.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "additional_text.dtd">
<texts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="additional_text.xsd">
	<text id="intro">
		<croatian>
			<p>Na drugom medunarodnom kongresu podzemne topografije (odrzanom u Breitenbachu, Svicarska, 1995.) na dnevnom redu nasli su se speleoloski simboli pojedinih zemalja. Najznacajniji simboli bili su prihvaceni na novi zajednicki popis, te objavljeni kao prijedlog medunarodnog popisa speleoloskih simbola. Ovaj prijedlog bio je predmet rasprave i na UIS kongresu u La Chaux de Fonds, te tamo i izglasan od strane delegata svih zemalja.</p>
			<p>Popis simbola bi trebao biti opsezna medunarodna osnova, na koju svaka zemlja moze, prema potrebi, dodati vlastite simbole. Stoga nije zabranjeno rabiti dodatne smislene simbole.</p>
			<p>Raspravom medu aktivnim mjernicima i crtacima doslo se do zakljucka da je nacrt sa svim svojim simbolima i napomenama tek polovica zadovoljavajuce dokumentacije o speleoloskom objektu. Drugi, takoder vrlo vazni dio dokumentacije je opsezan opis objekta, ukljucujuci i fenomene koji se ne mogu skicirati na nacrtu. Napisan opis je stoga vrlo vazan faktor pri dokumentiranju speleoloskog objekta. Opazanja o geoloskoj strukturi , sedimentima, klimatskim uvjetima, hidrologiji, kao i o flori i fauni, opis lokacije i puta do ulaza, kratki sazetak o povjesti istrazivanja, kao i popis potrebne opreme tocke su opsezne dokumentacije speloloskog objekta. Pretpostavke o mogucnosti nastavka galerija, te teorije o nastanku pojedinih kanala zaokruzuju opis speleoloskog objekta i zajedno sa dobrim nacrtom tvore vrijednu osnovu za daljnji rad.</p>
			<p>Stoga se preporuca ne samo crtanje nacrta (tlocrta i ispruzenog profila) speleoloskog objekta, vec i opisivanje objekta rjecima.</p>
		</croatian>
		<dutch>
			<p>At the "Second International Meeting on subterrainean Topography" in Breitenbach (Switzerland), 1995, Cave Signature lists of different countries had been the subject of discusssion. The essential symbols had been integrated into a new list and published as a proposal of an international cave signature list. This proposal has been debated thoroughly at the UIS congress in La Chaux de Fonds and then voted and accepted by the national delegates of each country.</p>
			<p>This list should be a comprehensive, international foundation, on which each country can, if necessary, introduce their own additional symbols. It is therefore not forbidden to use additional meaningful symbols.</p>
			<p>Among active surveyors and draftsmen it turned out, that the plan with all its symbols and signatures is only "half" of the work, documenting a cave-system. The other, also very important part is a comprehensive description of the system, including phenomena that can't be sketched in a map. The written cave-description therefore is a very important factor in documenting the cave. Observing geology, sediments, climatic conditions, hydrology as well as watching fauna and flora, describing the location and path to the cave entrance, an abstract on the history of exploration, last not least lists on needed equipment, all those points belong to a comprehensive cave documentaion.</p>
			<p>Assumptions on continuations of galleries just as theories on the genesis of a certain passage round up the cave description and form together with a welldone cave map a valuable foundation for further work.</p>
			<p>It is therefore recommended, not only to sketch a cave plan and a developed section (see documentation on the 9th National Congress 1991, Charmey), but also the cave description mentioned above!</p>
		</dutch>
		<english>
			<p>At the "Second International Meeting on subterrainean Topography" in Breitenbach (Switzerland), 1995, Cave Signature lists of different countries had been the subject of discusssion. The essential symbols had been integrated into a new list and published as a proposal of an international cave signature list. This proposal has been debated thoroughly at the UIS congress in La Chaux de Fonds and then voted and accepted by the national delegates of each country.</p>
			<p>This list should be a comprehensive, international foundation, on which each country can, if necessary, introduce their own additional symbols. It is therefore not forbidden to use additional meaningful symbols.</p>
			<p>Among active surveyors and draftsmen it turned out, that the plan with all its symbols and signatures is only "half" of the work, documenting a cave-system. The other, also very important part is a comprehensive description of the system, including phenomena that can't be sketched in a map. The written cave-description therefore is a very important factor in documenting the cave. Observing geology, sediments, climatic conditions, hydrology as well as watching fauna and flora, describing the location and path to the cave entrance, an abstract on the history of exploration, last not least lists on needed equipment, all those points belong to a comprehensive cave documentaion.</p>
			<p>Assumptions on continuations of galleries just as theories on the genesis of a certain passage round up the cave description and form together with a welldone cave map a valuable foundation for further work.</p>
			<p>It is therefore recommended, not only to sketch a cave plan and a developed section (see documentation on the 9th National Congress 1991, Charmey), but also the cave description mentioned above!</p>
		</english>
		<french>
			<p>A la deuxième réunion internationale de topographie à Breitenbach (Suisse), en 1995, les différentes listes de symboles utilisés en topographie ont été discutées. Les symboles importants ont été reportés dans une nouvelle liste qui a été publiée comme proposition d'une liste internationale. Cette proposition a été discutée en profondeur au Congrès international UIS de la Chaux-de-Fonds en 1997. Elle a été votée et acceptée par des délégués nationaux.</p>
			<p>Cette liste doit servir de base internationale pour la communication. Les différents pays peuvent s'y appuyer et la compléter si besoin est par des listes annexes.</p>
			<p>Les spéléo-topographes actifs ont atteint le consensus selon lequel le plan et tous ses symboles ne représentent que la moitié du travail à faire. L'autre moitié, tout aussi importante, consiste en une description de la cavité. Cette description, présentant des faits qui ne peuvent pas être portés dans le plan, gagne ainsi en importance. Les observations sur la géologie, la sédimentologie, l'hydrologie et le climat, la flore et la faune, la description des accès et l'histoire des explorations, sans oublier la liste des équipements, font intégralement partie de la documentation écrite de la cavité. Les continuations supposées, les hypothèses et théories sur la formation de la grotte complètent les informations et donnent avec le plan une base précieuse pour les travaux futurs.</p>
			<p>Il est recommandé non seulement de dessiner un plan et une coupe longitudinale (non projetée), mais également de faire une description de la cavité comme mentionné ci-dessus.</p>
		</french>
		<german>
			<p>Am zweiten internationalen Treffen für unterirdische Topographie in Breitenbach (Schweiz) 1995 wurden die Signaturlisten der verschiedenen Länder einer Prüfung unterzogen. Die wesentlichen Symbole wurden in eine neue Liste integriert, die dann als Vorschlag für eine internationale Signaturliste veröffentlicht wurde. Dieser Vorschlag wurde dann am UIS-Kongress ausgiebig debattiert und im Anschluss von den nationalen Delegierten der UIS genehmigt.</p>
			<p>Diese Liste versteht sich als internationale Verständigungsbasis, auf dessen Grundlage die einzelnen Länder, falls dies für nötig erachtet wird, ihre eigenen Zusatzlisten aufbauen können. Es ist also nicht verboten, weitere Signaturen zu benützen!</p>
			<p>Es kristallisierte sich bei den aktiven Höhlenvermessern immer mehr heraus, dass der Plan mit allen seinen Zeichen und Signaturen immer nur die "Hälfte" der Arbeit eines Höhlenforschers darstellt. Die andere, ebenso wichtige, Hälfte besteht aus einer Beschreibung der Höhle, in der Dinge, die nicht im Plan gezeichnet werden können, niedergeschrieben werden. Die Höhlenbeschreibung erhält so einen grösseren Stellwert. Beobachtungen zur Geologie, Sedimentologie, zur Hydrologie und zum Klima, zur Flora und Fauna, dazu die Zugangsbeschreibung und ein geschichtlicher Abriss der Forschungsgeschichte, nicht zu vergessen allfällige Einrichtungslisten, all dies gehört in eine schriftliche Höhlenbeschreibung. Vermutungen über mögliche Gangfortsetzungen sowie vielleicht eine Theorie über die Höhlenentstehung runden den Text ab und machen ihn, zusammen mit dem Plan, zur wertvollen Basis für alle weiteren Arbeiten.</p>
			<p>Es ist daher dringend empfohlen, nicht nur einen Grundriss und einen (abgewickelten) Längsschnitt (siehe Akten des 9. Nationalen Kongresses 1991, Charmey) zu erstellen, sondern auch die oben erwähnte Höhlenbeschreibung!</p>
		</german>
		<italian>
			<p>Durante il "Secondo Incontro Internazionale di Topografia sotterranea" a Breitenbach (Svizzera), 1995, sono state discusse liste di simboli speleologici presentate da diversi paesi. I simboli essenziali sono stati integrati in una nuova lista e pubblicati sottoforma di proposta per una lista internazionale. Questa proposta é stata dibattuta esaurientemente al congresso dell'UIS a La Chaux de Fonds ed é stata accettata in votazione dai delegati di ogni nazione.</p>
			<p>Questa lista va interpretata come base d'intesa internazionale su cui, qualora si rendesse necessario, i singoli Paesi possono fondare la costituzione delle proprie liste accessorie.</p>
