=== GrottoCenter/UIS_Cave_symbols/guiElements.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT croatian (#PCDATA)>
<!ELEMENT dutch (#PCDATA)>
<!ELEMENT english (#PCDATA)>
<!ELEMENT french (#PCDATA)>
<!ELEMENT german (#PCDATA)>
<!ELEMENT guiElement (croatian, dutch, english, french, german, italian, polish, portuguese, romanian, slovene, spanish, turkish, arabic)>
<!ATTLIST guiElement
	id ID #REQUIRED
>
<!ELEMENT guiElements (guiElement+)>
<!ATTLIST guiElements
	xmlns:xsi CDATA #REQUIRED
	xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!ELEMENT italian (#PCDATA)>
<!ELEMENT polish (#PCDATA)>
<!ELEMENT portuguese (#PCDATA)>
<!ELEMENT romanian (#PCDATA)>
<!ELEMENT slovene (#PCDATA)>
<!ELEMENT spanish (#PCDATA)>
<!ELEMENT turkish (#PCDATA)>
<!ELEMENT arabic (#PCDATA)>

=== GrottoCenter/UIS_Cave_symbols/guiElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guiElements SYSTEM "guiElements.dtd">
<guiElements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guiElements.xsd">
	<guiElement id="title">
		<croatian>Konacna lista UIS speleoloskih simbola</croatian>
		<dutch>Cave Symbols: The Official UIS List</dutch>
		<english>Cave Symbols: The Official UIS List</english>
		<french>UIS signes conventionnels: la liste définitive</french>
		<german>UIS-Höhlensignaturen: Die definitive Liste</german>
		<italian>UIS-Simboli speleologici: La lista definitiva</italian>
		<polish>Symbole jaskiniowe: Oficjalna lista UIS</polish>
		<portuguese>Simbologia de caverna da UIS: A lista definitiva</portuguese>
		<romanian>Semnele conventionale UIS: listă definitivă</romanian>
		<slovene>Nabor znakov UIS</slovene>
		<spanish>Símbología de cuevas: La Lista Oficial de la UIS</spanish>
		<turkish>Mağara Sembolleri - Resmi USB Listesi</turkish>
	</guiElement>
	<guiElement id="UISworkingGroup">
		<croatian>Radna grupa UIS "Topografija i crtanje spilja"</croatian>
		<dutch>UIS working group on cave survey and mapping</dutch>
		<english>UIS working group on cave survey and mapping</english>
		<french>UIS groupe de travail "Topographie et dessin"</french>
		<german>UIS-Arbeitsgruppe "Topographie und Höhlenplanzeichnung"</german>
		<italian>Gruppo di Lavoro UIS "Topografia e schizzi di grotta"</italian>
		<polish>Gruba robocza UIS "Kartowanie i planowanie jaskiń"</polish>
		<portuguese>Grupo de trabalho da UIS "Topografia e Mapeamento de cavernas"</portuguese>
		<romanian>Grupul de lucru UIS "Topografie şi desen"</romanian>
		<slovene>Delovna skupina UIS "Topografija in risanje jam"</slovene>
		<spanish>Grupo de trabajo de la UIS "Topografía y mapeo de cuevas"</spanish>
		<turkish>Uluslararası Mağarabilim Birliği UMB Çalışma Grubu "Mağara Araştırma ve Haritalama"</turkish>
	</guiElement>
	<guiElement id="languageChoice">
		<croatian>Back to Language Choice</croatian>
		<dutch>Back to Language Choice</dutch>
		<english>Back to Language Choice</english>
		<french>Back to Language Choice</french>
		<german>Zurück zur Sprachwahl</german>
		<italian>Back to Language Choice</italian>
		<polish>Powrót do wyboru języka</polish>
		<portuguese>Back to Language Choice</portuguese>
		<romanian>Înapoi la selecţia limbii</romanian>
		<slovene>Back to Language Choice</slovene>
		<spanish>Regresar a selección de idioma</spanish>
		<turkish>Dil Seçimine Geri Dön</turkish>
	</guiElement>
	<guiElement id="introList">
		<croatian>Uvod</croatian>
		<dutch>Introductie op de lijst</dutch>
		<english>Introduction to the List</english>
		<french>Introduction de la liste</french>
		<german>Einführung in die Liste</german>
		<italian>Introduzione alla lista</italian>
		<polish>Wprowadzenie do listy</polish>
		<portuguese>Introdução à lista</portuguese>
		<romanian>Introducere</romanian>
		<slovene>Uvod k seznamu</slovene>
		<spanish>Introducción a la lista</spanish>
		<turkish>Listeye Giriş</turkish>
	</guiElement>
	<guiElement id="bibliography">
		<croatian>Literatura</croatian>
		<dutch>Bibliografie</dutch>
		<english>Bibliography</english>
		<french>Bibliographie</french>
		<german>Literatur</german>
		<italian>Bibliografia</italian>
		<polish>Bibliografia</polish>
		<portuguese>Bibliografia</portuguese>
		<romanian>Bibliografie</romanian>
		<slovene>Bibliografija</slovene>
		<spanish>Bibliografía</spanish>
		<turkish>Kaynakça</turkish>
	</guiElement>
	<guiElement id="aboutAuthors">
		<croatian>O autoru</croatian>
		<dutch>Over de auteur</dutch>
		<english>About the authors</english>
		<french>Sur les Auteurs</french>
		<german>Über die Autoren</german>
		<italian>Autori</italian>
		<polish>Autorzy</polish>
		<portuguese>Sobre os Autores</portuguese>
		<romanian>Despre autori</romanian>
		<slovene>O avtorju</slovene>
		<spanish>Sobre los autores</spanish>
		<turkish>Yazarlar</turkish>
	</guiElement>
	<guiElement id="selectOneOfFollowing">
		<croatian>Molimo izaberite jedan od navedenih simbola:</croatian>
		<dutch>Kies een van de volgende symbolen:</dutch>
		<english>Please select one of the following symbols:</english>
		<french>Choisissez parmi les symboles suivants, s.v.p.:</french>
		<german>Bitte wählen Sie aus den folgenden Symbolen:</german>
		<italian>Seleziona uno dei seguenti simboli:</italian>
		<polish>Proszę wybrać jeden z poniższych symboli:</polish>
		<portuguese>Por favor, selecione um dos símbolos a seguir:</portuguese>
		<romanian>Vă rugăm să selectaţi unul din următoarele simboluri:</romanian>
		<slovene>Prosim izberite enega od spodaj nastetih znakov:</slovene>
		<spanish>Por favor seleccione uno de los siguientes símbolos:</spanish>
		<turkish>Lütfen aşağıdaki sembollerden birini seçiniz:</turkish>
	</guiElement>
	<guiElement id="planSymbol">
		<croatian>Simbol na tlocrtu</croatian>
		<dutch>Symbool plattegrond</dutch>
		<english>Symbol Plan</english>
		<french>Symbole-Plan</french>
		<german>Symbol Plan</german>
		<italian>Simbolo di pianta</italian>
		<polish>Symbol w planie</polish>
		<portuguese>Símbolo em planta</portuguese>
		<romanian>Simbol Plan</romanian>
		<slovene>Znak na tlorisu</slovene>
		<spanish>Símbolo de planta</spanish>	
		<turkish>Plan Sembolü</turkish>
	</guiElement>
	<guiElement id="profileSymbol">
		<croatian>Simbol u profilu</croatian>
		<dutch>Symbool doorsnede</dutch>
		<english>Symbol Profile</english>
		<french>Symbole-Coupe</french>
		<german>Symbol Längsschnitt</german>
		<italian>Simbolo di sezione</italian>
		<polish>Symbol w przekroju</polish>
		<portuguese>Símbolo em perfil</portuguese>
		<romanian>Simbol Profil</romanian>
		<slovene>Znak na iztegnjenem profilu</slovene>
		<spanish>Símbolo de perfil</spanish>
		<turkish>Kesit Sembolü</turkish>
	</guiElement>
	<guiElement id="explanations">
		<croatian>Pojasnjenje</croatian>
		<dutch>Uitleg</dutch>
		<english>Explanations</english>
		<french>Explication</french>
		<german>Erklärung</german>
		<italian>Spiegazione</italian>
		<polish>Objaśnienia</polish>
		<portuguese>Explicações</portuguese>
		<romanian>Explicaţii</romanian>
		<slovene>Obrazlozitev</slovene>
		<spanish>Explicaciones</spanish>
		<turkish>Açıklamalar</turkish>
	</guiElement>
	<guiElement id="translations">
		<croatian>Prijevodi</croatian>
		<dutch>Vertalingen</dutch>
		<english>Translations</english>
		<french>Traduction</french>
		<german>Übersetzungen</german>
		<italian>Traduzioni</italian>
		<polish>Tłumaczenia</polish>
		<portuguese>Traduções</portuguese>
		<romanian>Traduceri</romanian>
		<slovene>Prevodi</slovene>
		<spanish>Traducciones</spanish>
		<turkish>Çeviri</turkish>
	</guiElement>
	<guiElement id="photos">
		<croatian>Photos</croatian>
		<dutch>Photos</dutch>
		<english>Photos</english>
		<french>Photos</french>
		<german>Fotos</german>
		<italian>Photos</italian>
		<polish>Zdjęcia</polish>
		<portuguese>Photos</portuguese>
		<romanian>Fotografii</romanian>
		<slovene>Photos</slovene>
		<spanish>Fotos</spanish>
		<turkish>Fotoğraflar</turkish>
	</guiElement>
	<guiElement id="selectAllSymbols">
		<croatian>Izaberi sve simbole</croatian>
		<dutch>Selecteer alle symbolen</dutch>
		<english>Select All Symbols</english>
		<french>Sélectionner tous les symboles</french>
		<german>Selektiere alle Symbole</german>
		<italian>Seleziona tutti i simboli</italian>
		<polish>Zaznacz wszystkie</polish>
		<portuguese>Selecione todos os Símbolos</portuguese>
		<romanian>Selectaţi toate simbolurile</romanian>
		<slovene>Isberi vse znake</slovene>
		<spanish>Seleccionar todos los símbolos</spanish>
		<turkish>Bütün Sembolleri Seç</turkish>
	</guiElement>
	<guiElement id="selectNoSymbol">
		<croatian>Ponisti izbor</croatian>
		<dutch>Selecteer geen symbool</dutch>
		<english>Select No Symbol</english>
		<french>Annuler la sélection</french>
		<german>Selektiere kein Symbol</german>
		<italian>Non selezionare simboli</italian>
		<polish>Usuń zaznaczenie</polish>
		<portuguese>Limpar Seleção</portuguese>
		<romanian>Deselectaţi tot</romanian>
		<slovene>Ne izberi nobenega</slovene>
		<spanish>Deseleccionar símbolos</spanish>
		<turkish>Sembolü Seçme</turkish>
	</guiElement>
	<guiElement id="invertSelection">
		<croatian>Invertiraj izbor</croatian>
		<dutch>Draai selectie om</dutch>
		<english>Invert Selection</english>
		<french>Inverser la sélection</french>
		<german>Invertiere Auswahl</german>
		<italian>Inverti la selezione</italian>
		<polish>Odwróć zaznaczenie</polish>
		<portuguese>Inverter Seleção</portuguese>
		<romanian>Inversaţi Selecţia</romanian>
		<slovene>Preobrni izbor</slovene>
		<spanish>Invertir selección</spanish>
		<turkish>Diğerlerini Seç</turkish>
	</guiElement>
	<guiElement id="showSelectedSymbols">
		<croatian>Prikazi izabrane simbole</croatian>
		<dutch>Laat geselecteerde symbolen zien</dutch>
		<english>Show Selected Symbols</english>
		<french>Afficher les symboles sélectionnés</french>
		<german>Zeige ausgewählte Symbole</german>
		<italian>Mostra i simboli selezionati</italian>
		<polish>Pokaż zaznaczone symbole</polish>
		<portuguese>Mostre os Símbolos selecionados</portuguese>
		<romanian>Arată simbolurile selecţionate</romanian>
		<slovene>Prikazi izbrane znake</slovene>
		<spanish>Mostrar símbolos seleccionados</spanish>
		<turkish>Seçilen Sembolleri Göster</turkish>
	</guiElement>
	<guiElement id="somePlatformsRequire">
		<croatian>Kod nekih pretrazivaca morate pritisnuti tipke Shift i/ili Ctrl ukoliko zelite izabrati vise simbola odjednom.</croatian>
		<dutch>Sommige platforms (Browsers) vragen om Shift/en/of/Ctrl toetsen om meer symbolen tegelijk te kunnen selecteren.</dutch>
		<english>Some platforms (Browsers) require Shift/and/or/Ctrl Key for selection of multiple symbols.</english>
		<french>Pour sélectionner plusieurs symboles, certains systèmes demandent d'actionner les touches ctrl et/ou shift.</french>
