=== GrottoCenter/UIS_Cave_symbols/symbol_data.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Tobias Dahinden (Institute of Cartography) -->
<!--DTD generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<!ELEMENT cave_symbol (photos, translationsSymbolName, translationsExplanations)>
<!ATTLIST cave_symbol
	id ID #REQUIRED
	hasProfileSymbol (false | true) #REQUIRED
>
<!ELEMENT cave_symbols (cave_symbol+)>
<!ATTLIST cave_symbols
	xmlns:xsi CDATA #REQUIRED
	xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!ELEMENT croatian (#PCDATA)>
<!ELEMENT dutch (#PCDATA)>
<!ELEMENT english (#PCDATA)>
<!ELEMENT french (#PCDATA)>
<!ELEMENT german (#PCDATA)>
<!ELEMENT italian (#PCDATA)>
<!ELEMENT portuguese (#PCDATA)>
<!ELEMENT romanian (#PCDATA)>
<!ELEMENT slovene (#PCDATA)>
<!ELEMENT turkish (#PCDATA)>
<!ELEMENT photo (croatian, dutch, english, french, german, italian, portuguese, romanian, slovene, turkish)>
<!ATTLIST photo
	filename CDATA #REQUIRED
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	photographer CDATA #IMPLIED
	caveRegionName CDATA #IMPLIED
	year CDATA #IMPLIED
>
<!ELEMENT photos (photo*)>
<!ELEMENT translationsExplanations (croatian, dutch, english, french, german, italian, portuguese, romanian, slovene, turkish)>
<!ELEMENT translationsSymbolName (croatian, dutch, english, french, german, italian, portuguese, romanian, slovene, turkish)>

=== GrottoCenter/UIS_Cave_symbols/symbol_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cave_symbols SYSTEM "symbol_data.dtd">
<cave_symbols xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="symbol_data.xsd">
	<cave_symbol id="survey_points" hasProfileSymbol="true">
		<photos/>
		<translationsSymbolName>
			<croatian>Mjerne tocke</croatian>
			<dutch>Meetpunten</dutch>
			<english>Survey Points</english>
			<french>Point de relevé principal</french>
			<german>Messpunkte</german>
			<italian>Caposaldo principale</italian>
			<polish>Punkty ciągu pomiarowego</polish>
			<portuguese>Bases topográficas</portuguese>
			<romanian>Punct  topographic principal</romanian>
			<slovene>Merilne tocke</slovene>
			<spanish>Estaciones topográficas</spanish>
			<turkish>Ölçüm Noktası</turkish>
		</translationsSymbolName>
		<translationsExplanations>
			<croatian>Glavne mjerne tocke ostale su na popisu simbola, iako se cesto prikazuju samo na radnom orginalu.</croatian>
			<dutch>De hoofdmeetpunten worden meestal niet meer afgebeeld, maar ze blijven bewaard in een lijst.</dutch>
			<english>The main survey points have been kept in the list, but often they are no longer shown on fair copies.</english>
			<french>Les principaux points de relevé ont été gardés dans la liste, bien qu'ils soient souvent supprimés sur les topographies définitives.</french>
			<german>Die Messpunkte sind noch in der Liste verblieben, obwohl sie vielfach in den Reinzeichnungen nicht mehr verwendet werden.</german>
			<italian>I capisaldi principali sono stati mantenuti nella simbologia, ma /egraven facoltativo riportarli sul rilievo finale.</italian>
			<polish>Symbol głównych punktów ciągu pomiarowego został umieszczony na liście, mimo to, że w ostatecznej wersji rysunków często ciąg pomiarowy jest pomijany.</polish>
			<portuguese>As bases topográficas principais foram mantidas na lista, porém elas não são obrigatórias no mapa final.</portuguese>
			<romanian>Principalele puncte topografice au fost pastrate in lista, chiar daca multe sunt inlaturate din topografiile definitive.</romanian>
			<slovene>Glavne merilne tocke so ostale v seznamu, vendar se jih na nacrte pogosto ne rise vec.</slovene>
			<spanish>Las estaciones topográficas principales se mantienen en la lista, pero frecuentemente no se conservan en las copias en limpio.</spanish>
			<turkish>Ana ölçüm noktaları listede korunmuştur fakat sıklıkla temiz kopyalarda gösterilmemektedir.</turkish>
		</translationsExplanations>
	</cave_symbol>
	<cave_symbol id="outline_gallery" hasProfileSymbol="true">
		<photos/>
		<translationsSymbolName>
			<croatian>Stijene kanala/ galerije</croatian>
			<dutch>gang-omlijning</dutch>
			<english>Outline of a Gallery</english>
			<french>Dessin de galerie</french>
			<german>Gangumriss</german>
			<italian>Contorno della cavitr</italian>
			<polish>Przebieg ścian korytarza</polish>
			<portuguese>Contorno da galeria</portuguese>
			<romanian>Conturul galeriei</romanian>
			<slovene>Stene rova</slovene>
			<spanish>Contorno de la cueva</spanish>
			<turkish>Galeri Dış Çizgisi</turkish>
		</translationsSymbolName>
		<translationsExplanations>
			<croatian>Kao i do sada.</croatian>
			<dutch>spreekt voor zich.</dutch>
			<english>as before</english>
			<french>Comme auparavant</french>
			<german>wie zuvor</german>
			<italian>invariato</italian>
			<polish>jak poprzednio</polish>
			<portuguese>Conforme o anterior.</portuguese>
			<romanian>La fel ca inainte</romanian>
			<slovene>Kot do zdaj.</slovene>
			<spanish>Como antes</spanish>
			<turkish>Önceki İle Aynı</turkish>
		</translationsExplanations>
	</cave_symbol>
	<cave_symbol id="underlying_gallery" hasProfileSymbol="true">
		<photos/>
		<translationsSymbolName>
			<croatian>Kanal na nizoj etazi</croatian>
			<dutch>Onderliggende gang</dutch>
			<english>Underlying Passage</english>
			<french>Croisement de galeries</french>
			<german>Unterlagernde Gänge</german>
			<italian>Cavitr sottoposta</italian>
			<polish>Korytarz poniżej</polish>
			<portuguese>Passagem inferior</portuguese>
			<romanian>Galerii suprapuse</romanian>
			<slovene>Spodaj lezeci rov</slovene>
			<spanish>Pasaje inferior</spanish>
			<turkish>Altta Kalan Galeri</turkish>
		</translationsSymbolName>
		<translationsExplanations>
			<croatian>Da bi se kanal na nizoj etazi jace razlikovao od gornjeg kanala, preporuka je da se kanal na nizoj etazi prestane crtati i prije nego li se dodirne sa gornjim kanalom. Da bi se ovaj simbol jace razlikovao od simbola za pretpostavljenu velicinu galerije (nize), preporuca se da crte budu krace, a razmaci siri.</croatian>
			<dutch>Om de lagere gang te kunnen onderscheiden van de hogere gang, is het aan te raden om de lijnen van de lagere gang te stoppen voordat ze de hogere gang raken. Om dit lijntype te onderscheiden van de “geschatte maten van de ruimte” (zie daar) is het aan te raden om korte streepjes te tekenen met grote tussenruimten.</dutch>
			<english>As an additional help to distinguish the lower from the upper passage it is recommended to stop the line of the lower gallery before it reaches the upper gallery. To distinguish this symbol from the "presumed dimensions of space" (see below) it is recommended to draw short dashes with wide spacing.</english>
			<french>De façon à distinguer la galerie inférieure de la galerie supérieure, il est recommandé d'interrompre le dessin de la galerie inférieure avant qu'elle ne croise la supérieure. Pour distinguer ce symbole de celui des "Dimensions spatiales présumées" (voir ci-dessous) il est recommandé de dessiner des pointillés courts largement espacés.</french>
			<german>Als zusätzliche Hilfe, um unterlagernde von den Gängen darüber zu unterscheiden, wird empfohlen, die Linie des unterlagernden Ganges kurz vor dem Gang darüber abzusetzen. Um Verwechslungen mit den "Geschätzten Gangdimensionen" zu vermeiden, wird empfohlen, mit kurzen Strichen und weiten Abständen dazwischen zu zeichnen.</german>
			<italian>Come indicazione ulteriore per distinguere la cavitr sottostante dalla sovrapposta, si raccomanda di fermare la linea di contorno della cavitr sottoposta prima di raggiungere il contornodella cavitr sovrapposta. Per distinguere questo simbolo da quello di dimensioni presunte della cavitr (vedi sotto), si raccomanda di disegnare il tratteggio mediante tratti corti con ampia spaziatura.</italian>
			<polish>Dla łatwego rozróżnienia pomiędzy górnym a dolnym korytarzem, zaleca się przerwać linię dolnego korytarza przed przecięciem. Aby rozróżnić ten symbol od symbolu "szacowanych wymiarów korytarzy", zaleca się użycie krótkich kresek z długimi przerwami.</polish>
			<portuguese>Como ajuda adicional para se distinguir a passagem inferior da superior é recomendado descontinuar a linha da galeria inferior antes dela alcançar a superior. Para se distinguir este símbolo do "dimensão presumida" (vide abaixo) é recomendado desenhar pequenos traços com espaços maiores.</portuguese>
			<romanian>Ca si ajutor in distingerea galeriei inferioare fata de cea superioara e recomandat sa se opreasca desenarea liniei galeriei inferioare inainte de a o atinge pe cea a galeriei superioare. Pentru a nu-l  confunda cu simbolul  "Dimensiuni spatiale presupuse"  (vezi mai jos), se recomanda ca liniutele sa fie scurte cu spatii mari intre ele.</romanian>
			<slovene>Da bi se spodaj lezeci rov lazje locilo od zgornjega, se svetuje, da se crto spodnjega rova zakljuci malo preden doseze steno zgornjega rova. Da bi se ta znak locilo od znaka za predvideno velikost prostora (spodaj), morajo biti crtice kratke, prekinitve pa dolge.</slovene>
			<spanish>Como una ayuda adicional para distinguir el pasaje inferior del superior, se recomienda detener la línea del contorno del pasaje inferior antes de alcanzar la del pasaje superior. Para distinguir este símbolo de las "dimensiones inferidas del pasaje" (ver más adelante) se recomienda dibujar una línea punteada con trazos espaciados.</spanish>
			<turkish>Üst galeri ile alt galerinin ayırt edilmesinde ek bir yardım olarak; alttaki galerinin dış çizgisi üst galeriye yaklaştığı yerde bitirilmesi ve “varsayılan boşluk hacmi” sembolünden ayırmak için (aşağıya bakınız), geniş ve kısa çizgilerle çizilmesi önerilir.</turkish>
		</translationsExplanations>
	</cave_symbol>
	<cave_symbol id="too_narrow_continuation" hasProfileSymbol="true">
		<photos>
			<photo filename="too_narrow_continuation_1.jpg" width="397" height="600" photographer="Fabian Bels" caveRegionName="Gopital, Siebenhengste-Hohgant, Switzerland">
				<croatian>Preuski prolaz ...</croatian>
				<dutch>Te nauwe ...</dutch>
				<english>Too narrow ...</english>
				<french>Trop étroites ...</french>
				<german>Zu eng ...</german>
				<italian>Troppo stretta ...</italian>
				<portuguese>Estreita ...</portuguese>
				<romanian>Impenetrabil ...</romanian>
				<slovene>Preozko nadaljevanje ...</slovene>
				<spanish>Muy angosto ...</spanish>
				<turkish>Daralan Kol ...</turkish>
			</photo>
		</photos>
		<translationsSymbolName>
			<croatian>Preuski prolaz</croatian>
			<dutch>te nauwe doorgang</dutch>
			<english>Too narrow Continuation</english>
			<french>Continuations trop étroites</french>
			<german>Fortsetzung zu eng</german>
			<italian>Prosecuzione troppo stretta</italian>
			<polish>Zwężenie niemożliwe do przejścia</polish>
			<portuguese>Continuação estreita</portuguese>
			<romanian>Impenetrabil</romanian>
			<slovene>Preozko nadaljevanje</slovene>
			<spanish>Continuación muy angosta</spanish>
			<turkish>Daralan Kol</turkish>
		</translationsSymbolName>
		<translationsExplanations>
			<croatian>Kao i do sada.</croatian>
			<dutch>spreekt voor zich.</dutch>
			<english>as before</english>
			<french>Comme auparavant</french>
			<german>wie zuvor</german>
			<italian>invariato</italian>
			<polish>jak poprzednio</polish>
			<portuguese>Conforme o anterior.</portuguese>
			<romanian>La fel ca inainte</romanian>
			<slovene>Kot do zdaj.</slovene>
